// Generated by using rustinr::rustrize() -> do not edit by hand

use super::*;

#[no_mangle]
pub extern "C" fn rustr_acast_vec(ri : SEXP, ci : SEXP, values : SEXP, nrow : SEXP, ncol : SEXP, fill : SEXP)->SEXP{

 let ri_ : IntVec = unwrapr!( IntVec::rnew(ri) );

let ci_ : IntVec = unwrapr!( IntVec::rnew(ci) );

let values_ : NumVec = unwrapr!( NumVec::rnew(values) );

let nrow_ : usize = unwrapr!( usize::rnew(nrow) );

let ncol_ : usize = unwrapr!( usize::rnew(ncol) );

let fill_ : f64 = unwrapr!( f64::rnew(fill) );
 let res  = unwrapr!( acast_vec(ri_,ci_,values_,nrow_,ncol_,fill_));

 let res_sexp : SEXP = unwrapr!(res.intor());

 return res_sexp;
}

