// Generated by using rustinr::rustrize() -> do not edit by hand

#include <Rinternals.h>
#include <R.h>

extern SEXP rustr_acast_vec(SEXP ri, SEXP ci, SEXP values, SEXP nrow, SEXP ncol, SEXP fill);
SEXP mtercen_acast_vec(SEXP ri, SEXP ci, SEXP values, SEXP nrow, SEXP ncol, SEXP fill){ return(rustr_acast_vec(ri,ci,values,nrow,ncol,fill));}
